NAME = libftprintf.a

SOURCES =

FLAGS = -Wall -Wextra -Werror

OBJECTS = $(SOURCES:.c=.o)

all: $(NAME)
$(NAME): $(OBJECTS)
	ar rcs $(NAME) $(OBJECTS)

$(OBJECTS): $(SOURCES)
	cc -c $(Sources) -Includes $(flags)

clean:
	rm -f $(OBJECTS)

fclean: clean
	rm -f $(NAME)
re: fclean all

.PHONY: all clean fclean re Collapse
